# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: ['default', 'egl']
        build: ['debug', 'release']

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install libeigen3-dev libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev xvfb

    - name: Install extra dependencies
      run: sudo apt-get install qtbase5-dev libboost-iostreams-dev
      if: ${{ matrix.variant == 'default' }}

    - run: xvfb-run --server-args="-screen 0 1024x768x24+32" ./linux_build-${{ matrix.variant }}.bash
      env:
        BUILD: only_${{ matrix.build }}

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ${{ matrix.variant }}-${{ matrix-build }}-test_output
        path: build/make_${{ matrix.build }}/test/test_output/
