# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux_build:
    name: linux_build.sh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build default
      run: bash linux_build.sh

  linux_build-egl:
    name: linux_build-egl.sh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with EGL
      run: bash linux_build-egl.sh
