# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux_build-default:
    name: linux_build-default.sh
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ['only_debug', 'only_release']

    steps:
    - uses: actions/checkout@v4

    - name: Build default
      run: bash linux_build.bash
      env:
        BUILD: ${{ matrix.build }}

  linux_build-egl:
    name: linux_build-egl.sh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with EGL
      run: bash linux_build-egl.bash
      env:
        BUILD: ${{ matrix.build }}
